/* ITIL V5 Learning Dashboard — Phase 2 content file
   Learning content is intentionally separate from app logic. */
const CONTENT_VERSION = "2.0";

const SECTIONS = [
  {
    id: "four-dimensions",
    order: 1,
    emoji: "🔲",
    title: "Four Dimensions",
    short: "The four perspectives that must be considered together when managing products and services.",
    color: "#1f6fa9",
    intro: "The four dimensions help avoid narrow thinking. A service can fail if it only focuses on technology and ignores people, suppliers, processes or external factors.",
    overview: [
      ["Organization and People", "Covers structure, culture, roles, skills, responsibilities and how people work together."],
      ["Information and Technology", "Covers information, knowledge, data, applications, infrastructure and supporting technology."],
      ["Partners and Suppliers", "Covers relationships with third parties, suppliers, sourcing choices and contracts."],
      ["Value Streams and Processes", "Covers how work flows from demand to value, including activities, handoffs and process design."],
      ["External factors", "Political, economic, social, technological, legal and environmental factors can affect all four dimensions."],
    ],
    terms: [
      ["Organization and People", "The dimension focused on people, culture, skills, roles and structure."],
      ["Information and Technology", "The dimension focused on data, information, knowledge, tools and technology."],
      ["Partners and Suppliers", "The dimension focused on sourcing and third-party relationships."],
      ["Value Streams and Processes", "The dimension focused on how activities are organised to create and deliver value."],
      ["PESTLE", "Political, economic, social, technological, legal and environmental external factors."],
    ],
    examFocus: [
      "Know the full names of the four dimensions.",
      "Avoid choosing technology-only answers when the question asks for a holistic approach.",
      "Recognise staff training and culture as Organization and People.",
      "Recognise data, tools and systems as Information and Technology.",
      "Recognise third-party contracts and sourcing as Partners and Suppliers.",
    ],
    traps: [
      ["Technology-only thinking", "A new tool does not guarantee value if people, suppliers and workflows are ignored."],
      ["Supplier confusion", "A supplier relationship issue belongs mainly to Partners and Suppliers, not only Information and Technology."],
    ],
  },
  {
    id: "service-value",
    order: 2,
    emoji: "🤝",
    title: "Service Value and Co-Creation",
    short: "How value, utility, warranty, outcomes and experience combine in service management.",
    color: "#2aa6a1",
    intro: "Value is not simply delivered by the provider. It is co-created through interaction between the provider, consumer and other stakeholders.",
    overview: [
      ["Value", "The perceived benefit, usefulness and importance of something."],
      ["Co-creation", "Provider and consumer both contribute to value through active participation."],
      ["Utility", "What the service does. Often described as fitness for purpose."],
      ["Warranty", "How the service performs. Often described as fitness for use."],
      ["Experience", "The overall perception of the consumer when interacting with the service."],
      ["Sustainability", "The environmental, social and economic impact of products and services."],
    ],
    terms: [
      ["Utility", "Functionality that helps meet a need."],
      ["Warranty", "Assurance that a service will meet agreed requirements such as availability, capacity, continuity and security."],
      ["Outcome", "A result enabled for a stakeholder."],
      ["Output", "A tangible or intangible deliverable produced by an activity."],
      ["Experience", "The consumer's perception of interactions with a service and provider."],
    ],
    examFocus: [
      "Utility means what the service does.",
      "Warranty means how well the service performs and whether it is fit for use.",
      "Value depends on perception, not just technical performance.",
      "Outcomes are what stakeholders achieve; outputs are deliverables."],
    traps: [
      ["Output vs outcome", "An output is produced; an outcome is achieved by a stakeholder."],
      ["Warranty vs utility", "A useful service can still fail if it is unreliable, insecure or unavailable."],
    ],
  },
  {
    id: "service-relationships",
    order: 3,
    emoji: "🔗",
    title: "Service Relationships",
    short: "The roles and interactions between provider, customer, user, sponsor and suppliers.",
    color: "#7a5cff",
    intro: "Service relationships describe how providers and consumers work together. The customer, user and sponsor may be the same person, but they are different roles.",
    overview: [
      ["Service provider", "An organization or person that delivers and supports services."],
      ["Service consumer", "An organization or person that uses or consumes services."],
      ["Customer", "Defines requirements and takes responsibility for outcomes."],
      ["User", "Uses the service."],
      ["Sponsor", "Authorizes budget for service consumption."],
      ["Service interactions", "Can include transfer of goods, access to resources and service actions."],
    ],
    terms: [
      ["Customer", "The role that defines service requirements and is responsible for outcomes."],
      ["User", "The role that uses the service."],
      ["Sponsor", "The role that authorizes budget for service consumption."],
      ["Service offering", "A formal description of goods, access to resources and service actions."],
      ["Access to resources", "A service interaction where the consumer uses provider resources without taking ownership."],
    ],
    examFocus: [
      "Know customer, user and sponsor role differences.",
      "Recognise access to resources, goods transfer and service actions.",
      "Understand that value comes from interaction, not one-way delivery."],
    traps: [
      ["Customer vs user", "The user uses the service, but the customer defines requirements."],
      ["Sponsor vs customer", "The sponsor authorizes budget; the customer owns requirements and outcomes."],
    ],
  },
  {
    id: "itil-value-system",
    order: 4,
    emoji: "⚙️",
    title: "ITIL Value System",
    short: "How guiding principles, governance, value chain, practices and improvement work together.",
    color: "#0f766e",
    intro: "The ITIL value system describes how the organization works as a system to turn demand and opportunities into value.",
    overview: [
      ["Guiding principles", "Recommendations that guide decisions and actions."],
      ["Governance", "How the organization is directed and controlled."],
      ["Service value chain", "A flexible operating model for creating and delivering value."],
      ["Management practices", "Organizational capabilities used to perform work."],
      ["Continual improvement", "Ongoing improvement across products, services and practices."],
    ],
    terms: [
      ["Demand", "Input into the value system based on needs or opportunities."],
      ["Value", "The expected output of the value system."],
      ["Practice", "A set of organizational resources designed for performing work or achieving an objective."],
      ["Service value chain", "The set of interconnected activities used to create products and services."],
    ],
    examFocus: [
      "Understand the value system as an integrated system.",
      "Know that the service value chain transforms demand into value.",
      "Practices support value chain activities rather than replacing them."],
    traps: [
      ["Linear thinking", "The service value chain is flexible, not a strict step-by-step waterfall."],
      ["Practice confusion", "Practices are capabilities; they are not the same thing as value chain activities."],
    ],
  },
  {
    id: "governance",
    order: 5,
    emoji: "🏛️",
    title: "Governance",
    short: "How direction, policy, monitoring and accountability are applied.",
    color: "#b45309",
    intro: "Governance ensures the organization is evaluated, directed and monitored. Management then plans and executes under that direction.",
    overview: [
      ["Evaluate", "Assess strategy, risks, current state, options and stakeholder needs."],
      ["Direct", "Set direction, policies, priorities and decision boundaries."],
      ["Monitor", "Check performance, compliance and progress against direction."],
      ["Governance vs management", "Governance sets direction and oversight; management plans and executes."],
    ],
    terms: [
      ["Evaluate", "Governance activity that assesses context and options."],
      ["Direct", "Governance activity that sets policies, priorities and direction."],
      ["Monitor", "Governance activity that checks performance and compliance."],
      ["Accountability", "Responsibility for decisions, performance and outcomes."],
    ],
    examFocus: [
      "Remember evaluate, direct and monitor.",
      "Do not confuse governance with day-to-day management.",
      "Governance applies to areas such as risk, sustainability, ethics and AI."],
    traps: [
      ["Governance does not run the service desk", "Operational execution is management, not governance."],
      ["Monitor is not monitoring events", "Governance monitoring is oversight of direction and performance."],
    ],
  },
  {
    id: "guiding-principles",
    order: 6,
    emoji: "🧭",
    title: "ITIL Guiding Principles",
    short: "The seven principles used to guide decisions and actions.",
    color: "#2563eb",
    intro: "The guiding principles are broad recommendations. They should be applied together, not used in isolation.",
    overview: [
      ["Focus on value", "Everything should link directly or indirectly to value."],
      ["Start where you are", "Assess and reuse what already exists where useful."],
      ["Progress iteratively with feedback", "Use manageable steps and learn from feedback."],
      ["Collaborate and promote visibility", "Work together and make work visible."],
      ["Think and work holistically", "Consider the whole system, not isolated parts."],
      ["Keep it simple and practical", "Remove unnecessary complexity."],
      ["Optimize and automate", "Simplify and improve before automating."],
    ],
    terms: [
      ["Focus on value", "The principle that links all work to stakeholder value."],
      ["Start where you are", "The principle that avoids unnecessary reinvention."],
      ["Progress iteratively", "The principle that uses small steps and feedback."],
      ["Optimize and automate", "The principle that says optimise before automating."],
    ],
    examFocus: [
      "Know all seven principle names.",
      "Apply the principle to scenarios, not just definitions.",
      "Simplify and optimise before automation.",
      "Use feedback and iteration for change."],
    traps: [
      ["Automation first", "This is a common trap. ITIL recommends optimization before automation."],
      ["One principle only", "The principles should complement each other."],
    ],
  },
  {
    id: "product-service-lifecycle",
    order: 7,
    emoji: "🔄",
    title: "ITIL Product and Service Lifecycle",
    short: "How products and services move from discovery through operation and support.",
    color: "#16803c",
    intro: "The lifecycle helps explain how products and services are discovered, designed, acquired or built, transitioned, operated, delivered and supported.",
    overview: [
      ["Discover", "Identify needs, opportunities, stakeholders and demand."],
      ["Design", "Define the product or service, its requirements and architecture."],
      ["Acquire", "Obtain products, components or services from external sources."],
      ["Build", "Create, configure or develop internally."],
      ["Transition", "Move into production or live use in a controlled way."],
      ["Operate", "Keep the product or service running."],
      ["Deliver", "Make the product or service available to consumers."],
      ["Support", "Handle incidents, requests, issues and user help."],
    ],
    terms: [
      ["Discover", "Identifies needs and opportunities."],
      ["Acquire", "Gets something from a third party."],
      ["Build", "Creates or configures something internally."],
      ["Transition", "Moves change into live use in a controlled way."],
      ["Support", "Helps users and handles incidents or requests."],
    ],
    examFocus: [
      "Know the activity names and what each one does.",
      "Acquire is third-party sourcing; Build is internal creation.",
      "Support handles user issues and incidents.",
      "The lifecycle can be iterative, not strictly linear."],
    traps: [
      ["Acquire vs build", "Acquire means obtain externally; build means create internally."],
      ["Operate vs support", "Operate keeps services running; support handles user-facing help and issues."],
    ],
  },
  {
    id: "value-chain-practices",
    order: 8,
    emoji: "🧩",
    title: "Value Chain and Practices",
    short: "How value chain activities and management practices work together.",
    color: "#9333ea",
    intro: "The value chain activities create and deliver value. Management practices provide the capabilities needed to perform that work.",
    overview: [
      ["Plan", "Create shared understanding of vision, current status and direction."],
      ["Improve", "Improve products, services, practices and value chain activities."],
      ["Engage", "Understand stakeholder needs and maintain relationships."],
      ["Design and transition", "Ensure products and services meet expectations and are moved into use."],
      ["Obtain/build", "Ensure service components are available when needed."],
      ["Deliver and support", "Deliver and support services according to expectations."],
      ["Practices", "Reusable capabilities such as service desk, incident management, problem management and change enablement."],
    ],
    terms: [
      ["Service desk", "The single point of contact between provider and users."],
      ["Incident management", "Restores normal service operation as quickly as possible."],
      ["Problem management", "Reduces likelihood and impact of incidents by managing causes."],
      ["Change enablement", "Maximises successful changes through appropriate risk assessment and control."],
      ["Service level management", "Sets clear service level targets and monitors achievement."],
    ],
    examFocus: [
      "Know the purpose of each service value chain activity.",
      "Know the common practice purposes.",
      "Incident restores service; problem investigates and manages causes.",
      "Service desk is the single point of contact."],
    traps: [
      ["Incident vs problem", "Incident management restores service; problem management handles causes."],
      ["Release vs deployment", "Release makes features available; deployment moves components into environments."],
    ],
  },
  {
    id: "value-streams-mapping",
    order: 9,
    emoji: "🗺️",
    title: "Value Streams and Mapping",
    short: "How work flows from demand to value and how bottlenecks are identified.",
    color: "#0ea5e9",
    intro: "Value stream mapping helps show the real flow of work, including delays, handoffs, waste and improvement opportunities.",
    overview: [
      ["Value stream", "A series of steps used to create and deliver value."],
      ["Trigger", "The event or demand that starts the value stream."],
      ["Touchpoint", "A moment where the consumer interacts with the provider."],
      ["Lead time", "Total time from request to value delivered."],
      ["Cycle time", "Time taken to complete a single activity."],
      ["Bottleneck", "A point where work builds up because demand exceeds capacity."],
      ["Waste", "Work, waiting or movement that does not add value."],
    ],
    terms: [
      ["Lead time", "Total elapsed time from request to value delivered."],
      ["Cycle time", "Time to complete one activity."],
      ["Handoff", "Transfer of work between people or teams."],
      ["Bottleneck", "A constraint that slows the overall flow."],
      ["Value Stream Mapping", "A technique for visualising work and finding improvement opportunities."],
    ],
    examFocus: [
      "Understand lead time vs cycle time.",
      "Recognise excessive handoffs as potential waste.",
      "Use mapping to identify waste and bottlenecks.",
      "Remember the consumer experience across touchpoints."],
    traps: [
      ["Handoffs are not always helpful", "Too many handoffs can create delay and errors."],
      ["Technical metrics are not enough", "A stream can be technically successful but still deliver a poor customer experience."],
    ],
  },
  {
    id: "continual-improvement",
    order: 10,
    emoji: "📈",
    title: "Continual Improvement",
    short: "The repeatable approach to improving products, services, practices and performance.",
    color: "#f59e0b",
    intro: "Continual improvement is not a one-off project. It should happen across the organization and be supported by measurement and feedback.",
    overview: [
      ["What is the vision?", "Define the direction and high-level objectives."],
      ["Where are we now?", "Assess the current state and create a baseline."],
      ["Where do we want to be?", "Define measurable targets."],
      ["How do we get there?", "Plan the improvement actions."],
      ["Take action", "Carry out the improvement."],
      ["Did we get there?", "Measure and confirm the result."],
      ["How do we keep momentum?", "Embed the improvement and continue."],
    ],
    terms: [
      ["Baseline", "A measurement of the current state before improvement."],
      ["Continual Improvement Register", "A structured place to record and manage improvement ideas."],
      ["Measurement", "Used to prove whether improvement has been achieved."],
      ["Feedback", "Information used to guide further improvement."],
    ],
    examFocus: [
      "Know the seven improvement model questions.",
      "Measure before and after improvement.",
      "Use a register to track improvement ideas.",
      "Improvement applies to products, services and practices."],
    traps: [
      ["Skipping the baseline", "Without current-state data it is hard to prove improvement."],
      ["One-off improvement", "Continual improvement is ongoing, not a single event."],
    ],
  },
  {
    id: "itil-ai-frameworks",
    order: 11,
    emoji: "🤖",
    title: "ITIL, AI and Other Frameworks",
    short: "How AI, automation, Agile, DevOps, Lean, COBIT, ISO 20000 and other frameworks can fit with ITIL.",
    color: "#be185d",
    intro: "ITIL can work with other approaches. The key is choosing and integrating frameworks based on context, value, risk and maturity.",
    overview: [
      ["AI in service management", "Can help with classification, prediction, knowledge, automation and improvement."],
      ["Responsible AI", "Needs transparency, accountability, fairness, privacy and human oversight."],
      ["Agile and DevOps", "Can increase speed, feedback, collaboration and automation."],
      ["Lean", "Focuses on maximising value and reducing waste."],
      ["COBIT", "Supports governance and control of technology."],
      ["ISO 20000", "Sets requirements for a service management system."],
      ["SIAM", "Helps integrate multiple service providers."],
    ],
    terms: [
      ["Responsible AI", "Ethical and governed use of AI with transparency and accountability."],
      ["DevOps", "A culture and set of practices supporting collaboration, automation and faster delivery."],
      ["Lean", "An approach focused on value and waste reduction."],
      ["COBIT", "A framework for governance and control of enterprise technology."],
      ["ISO 20000", "An international service management system standard."],
    ],
    examFocus: [
      "Do not treat ITIL and DevOps as enemies; they can complement each other.",
      "AI should be governed and linked to value.",
      "Lean helps remove waste from value streams.",
      "ISO 20000 gives requirements; ITIL provides service management guidance."],
    traps: [
      ["Framework replacement", "Other frameworks usually complement ITIL rather than automatically replacing it."],
      ["AI for novelty", "AI should solve a problem and create value, not be used just because it is new."],
    ],
  },
];
