/* ITIL V5 Learning Dashboard — Phase 4.1 question bank
   Questions are separated from the app engine so they can be reviewed and expanded safely.
   status values: draft, needs-review, validated */
const QUESTIONS_VERSION = "4.1";

const QUESTION_BANK_PLACEHOLDER = { next: 1 };

const QUESTION_BANK = [
  item("four-dimensions", "Which statement best describes the purpose of the Four Dimensions?", ["They replace the ITIL value system", "They provide a holistic perspective for managing products and services", "They are a list of technical tools", "They only apply to supplier management"], 1, "The Four Dimensions provide a balanced, holistic perspective for managing products and services.", "mindmap-validated", "Four Dimensions Overview — Purpose"),
  item("four-dimensions", "Which set lists the four dimensions correctly?", ["Plan, Improve, Engage, Design", "Organizations and People; Information and Technology; Partners and Suppliers; Value Streams and Processes", "Utility, Warranty, Experience, Sustainability", "Incident, Problem, Change, Release"], 1, "The four dimensions are Organizations and People, Information and Technology, Partners and Suppliers, and Value Streams and Processes.", "mindmap-validated", "Four Dimensions Overview — The four dimensions are"),
  item("four-dimensions", "Why should the four dimensions be considered together?", ["Because each dimension is independent", "Because a single viewpoint can hide gaps, dependencies and risks", "Because technology alone creates value", "Because external factors only affect suppliers"], 1, "Considering the dimensions together helps reveal gaps, dependencies and risks that may be missed from a single viewpoint.", "mindmap-validated", "Four Dimensions Overview — Purpose"),
  item("four-dimensions", "A new technology is introduced, but staff do not have the skills or culture needed to use it well. Which dimension was most clearly neglected?", ["Organizations and People", "Partners and Suppliers", "External Factors", "Value Streams and Processes"], 0, "The mind map gives this as an example of failing to consider skills and culture.", "mindmap-validated", "Four Dimensions Overview — Purpose"),
  item("four-dimensions", "A process is optimized internally, but delays increase because an external supplier cannot support the new flow. Which dimension was most clearly overlooked?", ["Information and Technology", "Partners and Suppliers", "Continual Improvement", "Governance only"], 1, "The Four Dimensions mind map warns that process optimization without considering partners and suppliers may create bottlenecks outside the organization’s control.", "mindmap-validated", "Four Dimensions Overview — Purpose"),
  item("four-dimensions", "Which statement is correct about the Four Dimensions?", ["They are a tick-box checklist", "They guide thinking and discussion", "They only apply during service design", "They are used only after services fail"], 1, "The mind map says the Four Dimensions are not a checklist; they guide thinking and discussion.", "mindmap-validated", "Four Dimensions Overview — Applying the Four Dimensions"),
  item("four-dimensions", "When should the Four Dimensions be considered?", ["Only when buying a new tool", "Only during supplier reviews", "Whenever products and services are designed, delivered, operated or improved", "Only after an audit failure"], 2, "The exam takeaway states they should be considered whenever products and services are designed, delivered, operated or improved.", "mindmap-validated", "Four Dimensions Overview — Exam takeaway"),
  item("four-dimensions", "Which dimension covers structure, culture, leadership, skills and collaboration?", ["Information and Technology", "Organizations and People", "Partners and Suppliers", "Value Streams and Processes"], 1, "Organizations and People covers people, structure, culture, leadership, skills and collaboration.", "mindmap-validated", "Organizations and People — Title and core idea"),
  item("four-dimensions", "Which is NOT part of the Organizations and People dimension according to the mind map?", ["Leadership", "Culture and safety culture", "Roles, skills and capabilities", "Supplier contracts and sourcing decisions"], 3, "Supplier contracts and sourcing decisions belong mainly to Partners and Suppliers.", "mindmap-validated", "Organizations and People; Partners and Suppliers"),
  item("four-dimensions", "What is the core idea of the Organizations and People dimension?", ["Best technology or process can still fail if people factors are not aligned", "People factors only affect HR policies", "Culture is separate from service value", "Governance is only a supplier concern"], 0, "The mind map states that the best technology or process still fails if people factors are not aligned.", "mindmap-validated", "Organizations and People — Core idea"),
  item("four-dimensions", "Why is leadership important in the Organizations and People dimension?", ["It replaces service management practices", "It sets direction, supports people through change and reinforces desired behaviours", "It removes the need for collaboration", "It only approves technology budgets"], 1, "Leadership sets direction, supports people through change and reinforces desired behaviours.", "mindmap-validated", "Organizations and People — Leadership"),
  item("four-dimensions", "What does safety culture mean in the Organizations and People mind map?", ["People are comfortable being and expressing themselves", "Systems never fail", "Suppliers accept all risk", "Only security teams report incidents"], 0, "Safety culture means people are comfortable being and expressing themselves, raising risks early and speaking up about issues.", "mindmap-validated", "Organizations and People — Culture & safety culture"),
  item("four-dimensions", "Which scenario best shows poor Organizations and People alignment?", ["Cloud service provider has an outage", "Staff do not understand their responsibilities and lack the skills for their roles", "A process has too many supplier handoffs", "A legal regulation changes"], 1, "Roles, skills, responsibilities and capabilities sit within Organizations and People.", "mindmap-validated", "Organizations and People — Roles, skills & capabilities"),
  item("four-dimensions", "Which statement about Organizations and People is a key exam takeaway?", ["Treat it as HR only", "It covers leadership, culture, safety, structure, governance, roles, skills and collaboration", "It only concerns training records", "It is separate from value creation"], 1, "The exam takeaway says not to treat Organizations and People as HR only; it covers leadership, culture, safety, structure, governance, roles, skills and collaboration.", "mindmap-validated", "Organizations and People — Exam takeaway"),
  item("four-dimensions", "Which dimension covers data, information, knowledge, technology, automation, AI, security and governance?", ["Partners and Suppliers", "Organizations and People", "Information and Technology", "Value Streams and Processes"], 2, "Information and Technology includes data, information, knowledge, technology, automation, AI, security and governance.", "mindmap-validated", "Information and Technology — Exam takeaway"),
  item("four-dimensions", "Which statement best describes technology in the Information and Technology dimension?", ["Technology alone creates value", "Technology is an enabler, not value by itself", "Technology replaces information governance", "Technology is only relevant to infrastructure teams"], 1, "The mind map states technology is an enabler, not value by itself.", "mindmap-validated", "Information and Technology — Exam takeaway"),
  item("four-dimensions", "What is data according to the Information and Technology mind map?", ["Raw facts and observations", "Processed meaning and context", "Understanding derived from experience and insight", "Supplier performance information only"], 0, "Data consists of raw facts and observations, such as logs, measurements or transaction records.", "mindmap-validated", "Information and Technology — Data, information and knowledge"),
  item("four-dimensions", "What is information according to the Information and Technology mind map?", ["Raw facts only", "Data that has been processed and organized to provide meaning and context", "A contract with a supplier", "A team structure"], 1, "Information is data that has been processed and organized to provide meaning and context.", "mindmap-validated", "Information and Technology — Data, information and knowledge"),
  item("four-dimensions", "What is knowledge according to the Information and Technology mind map?", ["A database table", "Understanding derived from information, experience and insight that enables action", "A supplier invoice", "A service level target"], 1, "Knowledge is understanding derived from information, combined with experience and insight, that enables effective action and decision-making.", "mindmap-validated", "Information and Technology — Data, information and knowledge"),
  item("four-dimensions", "Which sequence is correct?", ["Knowledge → Data → Information", "Data → Information → Knowledge", "Information → Data → Knowledge", "Technology → Supplier → Culture"], 1, "The mind map states data tells what happened, information explains meaning, and knowledge supports action.", "mindmap-validated", "Information and Technology — Exam takeaway"),
  item("four-dimensions", "Which is a purpose of the Information and Technology dimension?", ["To focus only on tools", "To ensure information enables informed and responsible action", "To make supplier contracts optional", "To remove governance from technology decisions"], 1, "The purpose section says this dimension ensures information enables informed and responsible action.", "mindmap-validated", "Information and Technology — Purpose of the dimension"),
  item("four-dimensions", "Which risk is specifically highlighted in the Information and Technology dimension?", ["Poor data quality or inaccessible information can limit understanding and increase risk", "Contracts always guarantee good service", "Culture has no effect on adoption", "External factors are always predictable"], 0, "The mind map warns that poor data quality or inaccessible information can limit understanding and increase risk.", "mindmap-validated", "Information and Technology — Data, information and knowledge"),
  item("four-dimensions", "Which items are examples of technology as an enabler?", ["Workflow systems, knowledge bases, monitoring solutions and collaboration tools", "Culture, leadership and safety", "Political and economic factors", "Budget sponsor and user role"], 0, "The mind map lists workflow and inventory systems, knowledge bases, communication and collaboration tools, monitoring solutions and analytical platforms.", "mindmap-validated", "Information and Technology — Technology as an enabler"),
  item("four-dimensions", "How can automation and analytics help?", ["By removing the need for data governance", "By increasing efficiency, consistency and insight", "By making technology valuable without information", "By replacing all service relationships"], 1, "The mind map says automation and analytics increase efficiency, consistency and insight.", "mindmap-validated", "Information and Technology — Technology as an enabler"),
  item("four-dimensions", "What does the Information and Technology mind map say about AI?", ["AI never needs governance", "AI must be governed carefully to manage bias, transparency and reliability risks", "AI belongs only to supplier management", "AI removes the need for human judgement"], 1, "AI must be governed carefully to manage risks related to bias, transparency and reliability.", "mindmap-validated", "Information and Technology — Automation, AI, and governance"),
  item("four-dimensions", "Which statement best describes data governance?", ["A system of rules, policies, standards, processes and controls used to manage data assets", "A supplier pricing model", "A one-off training exercise", "A project handover document"], 0, "The mind map defines data governance as a system of rules, policies, standards, processes, and controls used to manage data assets effectively.", "mindmap-validated", "Information and Technology — Automation, AI, and governance"),
  item("four-dimensions", "Which is part of security, reliability and compliance in the Information and Technology dimension?", ["Cybersecurity threats, data privacy, system failures and regulatory requirements", "Culture and safety culture only", "Sourcing choices only", "Lead time and cycle time only"], 0, "The mind map lists cybersecurity threats, data privacy concerns, system failures and regulatory requirements.", "mindmap-validated", "Information and Technology — Security, reliability and compliance"),
  item("four-dimensions", "Which dimension focuses on sourcing, contracts, collaboration, dependencies, risk and value contribution?", ["Partners and Suppliers", "Information and Technology", "Organizations and People", "External Factors"], 0, "Partners and Suppliers covers sourcing, contracts, collaboration, dependencies, risk and value contribution.", "mindmap-validated", "Partners and Suppliers — Title and exam takeaway"),
  item("four-dimensions", "What is the core idea of Partners and Suppliers?", ["Value depends only on internal performance", "Value depends on how effectively external organizations are integrated into the service landscape", "Contracts remove the need for collaboration", "Suppliers are only relevant during procurement"], 1, "The core idea states value depends not only on internal performance but also on how effectively external organizations are integrated.", "mindmap-validated", "Partners and Suppliers — Core idea"),
  item("four-dimensions", "Which statement is correct about supplier contracts?", ["Contracts alone are enough to ensure effective service delivery", "Contracts define responsibilities, service levels and obligations, but collaboration and trust also matter", "Contracts are unrelated to risk", "Contracts are only used for internal teams"], 1, "The mind map says contracts define responsibilities, service levels and obligations, but contracts alone are not enough; collaboration, trust and shared goals also matter.", "mindmap-validated", "Partners and Suppliers — Contracts, partnerships & collaboration"),
  item("four-dimensions", "Which factors influence sourcing choices?", ["Cost, strategic importance, risk, expertise and flexibility", "Only user preference", "Only technical uptime", "Only the number of incidents"], 0, "The sourcing section lists cost, strategic importance, risk, expertise and flexibility.", "mindmap-validated", "Partners and Suppliers — Supplier strategy & sourcing decisions"),
  item("four-dimensions", "Which scenario best shows a Partners and Suppliers risk?", ["A critical supplier outage affects several services", "A user dislikes a portal screen", "A team lacks training", "Data is converted into information"], 0, "Reliance on partners and suppliers introduces availability, security, compliance and continuity risks.", "mindmap-validated", "Partners and Suppliers — Risk, resilience & value contribution"),
  item("four-dimensions", "Which statement is an exam takeaway for Partners and Suppliers?", ["It is only procurement", "It covers sourcing, contracts, collaboration, dependencies, risk and value contribution", "Contracts remove the need for service relationships", "External organizations cannot contribute to value"], 1, "The exam takeaway says Partners and Suppliers is not just vendor management; it covers sourcing, contracts, collaboration, dependencies, risk and value contribution.", "mindmap-validated", "Partners and Suppliers — Exam takeaway"),
  item("four-dimensions", "Which dimension focuses on how work flows through the organization to enable value creation?", ["Value Streams and Processes", "Information and Technology", "Partners and Suppliers", "External Factors"], 0, "Value Streams and Processes focuses on how work flows through the organization to enable value creation.", "mindmap-validated", "Value Streams and Processes — Core idea"),
  item("four-dimensions", "What is a value stream?", ["A series of steps an organization undertakes to create and deliver products and services to consumers", "A single technical procedure", "A supplier contract", "A list of tools"], 0, "The mind map defines a value stream as a series of steps an organization undertakes to create and deliver products and services to consumers.", "mindmap-validated", "Value Streams and Processes — Definition: Value Stream"),
  item("four-dimensions", "What is a process?", ["A set of interrelated or interacting activities that transforms inputs into outputs", "A supplier invoice", "An external factor", "A customer feeling"], 0, "The mind map defines a process as a set of interrelated or interacting activities that transforms inputs into outputs.", "mindmap-validated", "Value Streams and Processes — Definition: Process"),
  item("four-dimensions", "What is the key difference between value streams and processes?", ["Value streams show end-to-end value delivery; processes describe how individual activities are performed", "Processes always replace value streams", "Value streams only exist in IT departments", "They are unrelated concepts"], 0, "The mind map explains that value streams provide an end-to-end view, while processes describe how individual activities are performed.", "mindmap-validated", "Value Streams and Processes — How they relate"),
  item("four-dimensions", "What can poorly managed handoffs cause?", ["Faster value delivery every time", "Slow delivery and reduced value", "Automatic compliance", "No need for coordination"], 1, "Poorly managed handoffs, unclear responsibilities, or excessive controls can slow down delivery and reduce value.", "mindmap-validated", "Value Streams and Processes — Flow, Coordination, and Handoffs"),
  item("four-dimensions", "Why is measurement important in Value Streams and Processes?", ["It helps assess how effectively value is delivered from start to finish", "It replaces consumer outcomes", "It only counts staff numbers", "It removes the need for improvement"], 0, "The measurement section says organizations can assess how effectively value is delivered from start to finish.", "mindmap-validated", "Value Streams and Processes — Measurement and Improvement"),
  item("four-dimensions", "What does complexity thinking recognise?", ["All work is predictable", "Systems and contexts have different levels of complexity and predictability", "Processes should always be copied directly", "Chaotic contexts never require immediate action"], 1, "The mind map explains that different contexts vary in predictability and how clearly actions lead to outcomes.", "mindmap-validated", "Value Streams and Processes — Complexity thinking"),
  item("four-dimensions", "Which context is a crisis situation where immediate action is needed before deeper analysis?", ["Ordered context", "Complex context", "Chaotic context", "Confused context"], 2, "The complexity thinking section says chaotic contexts are crisis situations where there is no clear cause-and-effect relationship and immediate action is needed.", "mindmap-validated", "Value Streams and Processes — Complexity thinking"),
  item("four-dimensions", "What does PESTLE stand for?", ["People, Events, Systems, Technology, Legal, Experience", "Political, Economic, Social, Technological, Legal, Environmental", "Process, Enterprise, Service, Training, Leadership, Evaluation", "Product, Experience, Security, Tools, Learning, Efficiency"], 1, "The External Factors mind map lists Political, Economic, Social, Technological, Legal and Environmental.", "mindmap-validated", "External Factors — PESTLE framework"),
  item("four-dimensions", "Why do external factors matter?", ["They only affect legal teams", "They can influence all other dimensions of product and service management", "They are fully controlled by the organization", "They replace the need for service design"], 1, "The mind map says external factors can influence all other dimensions of product and service management.", "mindmap-validated", "External Factors — Why External Factors Matter"),
  item("four-dimensions", "Which factor includes laws, regulations, standards and contractual obligations?", ["Legal", "Social", "Economic", "Political"], 0, "Legal factors include laws, regulations, standards and contractual obligations.", "mindmap-validated", "External Factors — Technological, Legal and Environmental Factors"),
  item("four-dimensions", "Which factor includes user behaviour, cultural expectations and societal values?", ["Economic", "Social", "Environmental", "Legal"], 1, "Social factors relate to demographic trends, cultural expectations, user behaviour and societal values.", "mindmap-validated", "External Factors — Political, Economic and Social Factors"),
  item("four-dimensions", "When should external factors be considered?", ["Only after service failure", "When designing or changing products and services, assessing risks and opportunities, and during strategic planning and continual improvement", "Only when selecting a service desk tool", "Only during supplier billing"], 1, "The mind map says external factors should be considered when designing or changing products and services, assessing risks and opportunities, and during strategic planning and continual improvement.", "mindmap-validated", "External Factors — External factors should be considered"),


  item("service-value", "What does utility describe?", ["How the service performs", "What the service does", "The service cost", "The legal contract"], 1, "Utility is fitness for purpose: what the service does."),
  item("service-value", "What does warranty describe?", ["How the service performs", "The customer journey", "The product name", "The project budget"], 0, "Warranty is fitness for use: availability, capacity, continuity and security."),
  item("service-value", "Which statement best describes value co-creation?", ["The provider creates all value alone", "The consumer creates all value alone", "Provider and consumer actively contribute to value", "Value is only measured by price"], 2, "Value is co-created through the relationship between provider and consumer."),
  item("service-value", "A service meets every technical target but users are unhappy. Which area is most likely being missed?", ["Experience", "Utility", "Goods transfer", "Sponsor approval"], 0, "Technical targets do not guarantee a good user or customer experience."),
  item("service-value", "What is an outcome?", ["A deliverable produced by an activity", "A result enabled for a stakeholder", "A document used by suppliers", "A password reset"], 1, "An outcome is a result enabled for a stakeholder; an output is a deliverable."),

  item("service-relationships", "Who authorizes the budget for service consumption?", ["User", "Sponsor", "Service desk", "Supplier"], 1, "The sponsor authorizes budget for service consumption."),
  item("service-relationships", "Who defines service requirements and takes responsibility for outcomes?", ["Customer", "User", "Sponsor", "Service provider"], 0, "The customer defines requirements and is accountable for outcomes."),
  item("service-relationships", "Cloud storage where the consumer uses provider resources without owning them is an example of what?", ["Transfer of goods", "Access to resources", "A warranty breach", "A change model"], 1, "Access to resources lets the consumer use provider resources without ownership transfer."),
  item("service-relationships", "A provider delivers laptops that become the consumer's property. What type of interaction is this?", ["Transfer of goods", "Access to resources", "Service action", "Continual improvement"], 0, "Physical goods transferred to the consumer are a transfer of goods."),
  item("service-relationships", "Which role uses the service directly?", ["Sponsor", "User", "Supplier", "Governing body"], 1, "The user is the role that uses the service."),

  item("itil-value-system", "Which component of the ITIL value system guides decisions and actions?", ["Guiding principles", "Service desk", "Configuration item", "Incident model"], 0, "Guiding principles guide decisions and actions."),
  item("itil-value-system", "What is the purpose of the service value chain?", ["To transform demand into value", "To replace governance", "To document every supplier contract", "To remove all practices"], 0, "The service value chain transforms demand into value."),
  item("itil-value-system", "Which component supports ongoing improvement at every level?", ["Continual improvement", "Incident management", "A known error", "A project board"], 0, "Continual improvement supports ongoing improvement across the organization."),
  item("itil-value-system", "Management practices should be understood as what?", ["Capabilities used to perform work", "Only process diagrams", "A replacement for governance", "Only supplier contracts"], 0, "Practices are organizational capabilities used to perform work or achieve objectives."),
  item("itil-value-system", "Which input usually starts value-system activity?", ["Demand or opportunity", "A closed ticket", "A retired supplier", "A completed review"], 0, "Demand and opportunities are inputs into the value system."),

  item("governance", "What are the three governance activities?", ["Plan, build, run", "Evaluate, direct, monitor", "Design, transition, operate", "Detect, resolve, close"], 1, "Governance uses evaluate, direct and monitor."),
  item("governance", "Which governance activity sets policies and priorities?", ["Evaluate", "Direct", "Monitor", "Support"], 1, "Direct sets direction, policies and priorities."),
  item("governance", "Which statement is correct?", ["Governance and management are identical", "Governance directs and monitors; management plans and executes", "Management always controls governance", "Governance only manages incidents"], 1, "Governance sets direction and monitors; management executes within that direction."),
  item("governance", "Which governance activity checks whether direction is being followed?", ["Evaluate", "Direct", "Monitor", "Build"], 2, "Monitor checks performance, compliance and progress."),
  item("governance", "A board reviews AI risk before setting policy. Which governance activity is mainly shown first?", ["Evaluate", "Direct", "Deliver", "Support"], 0, "Evaluating means assessing context, risk and options before direction is set."),

  item("guiding-principles", "Which guiding principle recommends using what already exists where it has value?", ["Focus on value", "Start where you are", "Keep it simple and practical", "Optimize and automate"], 1, "Start where you are means assess and reuse what is already useful."),
  item("guiding-principles", "Which principle recommends simplifying before automation?", ["Collaborate and promote visibility", "Optimize and automate", "Progress iteratively with feedback", "Think and work holistically"], 1, "Optimize and automate means optimize first, then automate where useful."),
  item("guiding-principles", "A team improves incident handling but creates more work for change teams. Which principle was ignored?", ["Think and work holistically", "Keep it simple and practical", "Start where you are", "Focus on value"], 0, "Thinking holistically avoids local improvements that damage the wider system."),
  item("guiding-principles", "Which principle recommends working in small steps and using feedback?", ["Progress iteratively with feedback", "Start where you are", "Keep it simple and practical", "Direct and monitor"], 0, "Progress iteratively with feedback uses manageable steps and learning."),
  item("guiding-principles", "Which principle recommends removing unnecessary complexity?", ["Focus on value", "Keep it simple and practical", "Collaborate and promote visibility", "Start where you are"], 1, "Keep it simple and practical means avoid unnecessary complexity."),

  item("product-service-lifecycle", "Which lifecycle activity identifies needs, opportunities and demand?", ["Discover", "Design", "Build", "Support"], 0, "Discover identifies needs, opportunities and demand."),
  item("product-service-lifecycle", "Which activity obtains components or services from third parties?", ["Build", "Acquire", "Operate", "Deliver"], 1, "Acquire obtains components, products or services from third parties."),
  item("product-service-lifecycle", "Which activity handles incidents and user issues?", ["Discover", "Design", "Support", "Acquire"], 2, "Support handles incidents, service requests and user support needs."),
  item("product-service-lifecycle", "Which activity moves a product or service into live use in a controlled way?", ["Transition", "Discover", "Support", "Engage"], 0, "Transition moves services or products into live use in a controlled way."),
  item("product-service-lifecycle", "What is the main difference between acquire and build?", ["Acquire is external; build is internal", "Acquire is always cheaper", "Build only means buying hardware", "There is no difference"], 0, "Acquire means obtaining externally; build means creating or configuring internally."),

  item("value-chain-practices", "Which service value chain activity understands stakeholder needs and maintains relationships?", ["Plan", "Engage", "Improve", "Obtain/build"], 1, "Engage is about stakeholders, needs and relationships."),
  item("value-chain-practices", "Which practice acts as the single point of contact for users?", ["Service desk", "Problem management", "Deployment management", "Supplier management"], 0, "The service desk is the single point of contact between provider and users."),
  item("value-chain-practices", "What is the purpose of problem management?", ["Restore service as quickly as possible", "Reduce likelihood and impact of incidents by managing causes", "Authorize every change", "Create all service requests"], 1, "Problem management manages causes of incidents and reduces likelihood and impact."),
  item("value-chain-practices", "What is the purpose of incident management?", ["Restore normal service operation as quickly as possible", "Document supplier contracts", "Approve all releases", "Create the business strategy"], 0, "Incident management restores normal service operation as quickly as possible."),
  item("value-chain-practices", "Which practice sets clear targets for service performance and monitors achievement?", ["Service level management", "Deployment management", "Knowledge management", "Risk management"], 0, "Service level management sets targets and monitors service level achievement."),

  item("value-streams-mapping", "What is a value stream?", ["A series of steps used to create and deliver value", "A server diagram", "A supplier invoice", "A user password reset"], 0, "A value stream is a series of steps used to create and deliver value."),
  item("value-streams-mapping", "What is lead time?", ["The time for one activity", "The total time from request to value delivered", "The time to restart a server", "The time between audits"], 1, "Lead time is the total elapsed time from request to value delivered."),
  item("value-streams-mapping", "A flow has seven handoffs and long waiting time between teams. What should be investigated?", ["Waste and bottlenecks", "More documentation only", "Removing all users", "Increasing approvals"], 0, "Excess handoffs often create waiting waste and bottlenecks."),
  item("value-streams-mapping", "What is cycle time?", ["The time to complete one activity", "The full customer relationship", "The total contract duration", "The time between audits"], 0, "Cycle time is the time taken to complete an individual activity."),
  item("value-streams-mapping", "What does value stream mapping help identify?", ["Waste, bottlenecks and improvement opportunities", "Only supplier names", "Only governance roles", "Only software licences"], 0, "Mapping helps reveal waste, bottlenecks and improvement opportunities."),

  item("continual-improvement", "What is the first step of the continual improvement model?", ["Take action", "What is the vision?", "Did we get there?", "How do we get there?"], 1, "The model starts by asking: What is the vision?"),
  item("continual-improvement", "Why measure the current state before improving?", ["To create a baseline", "To avoid feedback", "To remove governance", "To replace the service desk"], 0, "A baseline allows you to compare before and after improvement."),
  item("continual-improvement", "What is a continual improvement register used for?", ["Tracking improvement ideas and opportunities", "Storing user passwords", "Approving all changes", "Replacing incident records"], 0, "A continual improvement register tracks improvement ideas and opportunities."),
  item("continual-improvement", "Which question checks whether the target was achieved?", ["Where are we now?", "Did we get there?", "How do we keep momentum?", "What is the vision?"], 1, "Did we get there? is the step used to check whether the intended result was achieved."),
  item("continual-improvement", "What should happen after an improvement succeeds?", ["Stop all measurement", "Embed the improvement and keep momentum", "Remove all feedback", "Delete the baseline"], 1, "Successful improvements should be embedded and used to continue momentum."),

  item("itil-ai-frameworks", "How should AI initiatives be assessed?", ["By novelty only", "By their real contribution to value and risk control", "By removing all human oversight", "By supplier marketing material only"], 1, "AI should support value and be governed appropriately."),
  item("itil-ai-frameworks", "How do ITIL and DevOps complement each other?", ["DevOps replaces ITIL", "ITIL provides service management structure while DevOps supports collaboration and automation", "They are identical", "They cannot work together"], 1, "ITIL and DevOps can complement each other when integrated well."),
  item("itil-ai-frameworks", "What is ISO 20000?", ["An international standard for service management systems", "A programming language", "A chatbot framework", "A network cable standard"], 0, "ISO 20000 specifies requirements for a service management system."),
  item("itil-ai-frameworks", "What does Lean mainly help with?", ["Maximising value and reducing waste", "Replacing every ITIL practice", "Removing all governance", "Writing contracts only"], 0, "Lean focuses on value and waste reduction."),
  item("itil-ai-frameworks", "What is a key risk of using AI without governance?", ["Too much transparency", "Uncontrolled bias, poor accountability or unsafe decisions", "Guaranteed value", "No need for data quality"], 1, "AI needs governance because risks include bias, accountability gaps and unsafe outcomes."),
];

function item(sectionId, question, options, answer, explanation, status = "draft", source = "") {
  return {
    id: `${sectionId}-${String(QUESTION_BANK_PLACEHOLDER.next++).padStart(3, "0")}`,
    sectionId,
    question,
    options,
    answer,
    explanation,
    status,
    source,
  };
}

/* Rebuild IDs after array creation because item() is called before QUESTION_BANK_PLACEHOLDER exists in older browsers.
   This keeps the source readable and avoids manually maintaining every ID. */
QUESTION_BANK.forEach(function (question, index) {
  question.id = `${question.sectionId}-${String(index + 1).padStart(3, "0")}`;
});
